// Includes every current card in Clash Royale

export const presetCards = [
  "Archer Queen",
  "Archers",
  "Arrows",
  "Baby Dragon",
  "Balloon",
  "Bandit",
  "Barbarian Barrel",
  "Barbarian Hut",
  "Barbarian",
  "Battle Ram",
  "Bats",
  "Battle Healer",
  "Berserker",
  "Bomb Tower",
  "Bomber",
  "Boss Bandit",
  "Bowler",
  "Cannon",
  "Cannon Cart",
  "Clone",
  "Dark Prince",
  "Dart Goblin",
  "Earthquake",
  "Electro Dragon",
  "Electro Giant",
  "Electro Spirit",
  "Electro Wizard",
  "Elite Barbarians",
  "Elixir Collector",
  "Elixir Golem",
  "Executioner",
  "Fire Spirit",
  "Fireball",
  "Firecracker",
  "Fisherman",
  "Flying Machine",
  "Freeze",
  "Furnace",
  "Giant",
  "Giant Skeleton",
  "Snowball",
  "Goblin Barrel",
  "Goblin Cage",
  "Goblin Curse",
  "Goblin Demolisher",
  "Goblin Drill",
  "Goblin Gang",
  "Goblin Giant",
  "Goblin Hut",
  "Goblin Machine",
  "Goblins",
  "Goblinstein",
  "Golden Knight",
  "Golem",
  "Graveyard",
  "Guards",
  "Heal Spirit",
  "Hog Rider",
  "Hunter",
  "Ice Golem",
  "Ice Spirit",
  "Ice Wizard",
  "Inferno Dragon",
  "Inferno Tower",
  "Knight",
  "Lava Hound",
  "Lightning",
  "Little Prince",
  "Lumberjack",
  "Magic Archer",
  "Mega Knight",
  "Mega Minion",
  "Mighty Miner",
  "Miner",
  "Mini Pekka",
  "Minion Horde",
  "Minions",
  "Mirror",
  "Monk",
  "Mortar",
  "Mother Witch",
  "Musketeer",
  "Night Witch",
  "Pekka",
  "Phoenix",
  "Poison",
  "Prince",
  "Princess",
  "Rage",
  "Ram Rider",
  "Rascals",
  "Rocket",
  "Royal Delivery",
  "Royal Ghost",
  "Royal Giant",
  "Royal Hogs",
  "Royal Recruits",
  "Rune Giant",
  "Skeleton Army",
  "Skeleton Barrel",
  "Skeleton Dragons",
  "Skeleton King",
  "Skeletons",
  "Sparky",
  "Spear Goblins",
  "Spirit Empress",
  "Suspicious Bush",
  "Tesla",
  "The Log",
  "Three Musketeers",
  "Tombstone",
  "Tornado",
  "Valkyrie",
  "Vines",
  "Void",
  "Wall Breakers",
  "Witch",
  "Wizard",
  "X-Bow",
  "Zap",
  "Zappies"
];